### ISSUE TITLE
Undefined method `match?' for /##?[^#]/:Regexp

### ISSUE THREAD

**Issue by r0adkll** [dblock/danger-changelog#51] opened 2019-08-22 19:27 UTC
`.check!` fails with the stacktrace:

```
Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined method `match?' for /##?[^#]/:Regexp
Did you mean?  match
 #  from Dangerfile:41
 #  -------------------------------------------
 #  changelog.placeholder_line = "- Your change(s) here."
 >  changelog.check!
 #  
 #  -------------------------------------------

  /Library/Ruby/Gems/2.3.0/gems/danger-changelog-0.6.0/lib/changelog/parsers/keep_a_changelog.rb:45:in `block in parse_into_blocks'
  /Library/Ruby/Gems/2.3.0/gems/danger-changelog-0.6.0/lib/changelog/parsers/keep_a_changelog.rb:42:in `each_line'
  /Library/Ruby/Gems/2.3.0/gems/danger-changelog-0.6.0/lib/changelog/parsers/keep_a_changelog.rb:42:in `each'
  /Library/Ruby/Gems/2.3.0/gems/danger-changelog-0.6.0/lib/changelog/parsers/keep_a_changelog.rb:42:in `parse_into_blocks'
  /Library/Ruby/Gems/2.3.0/gems/danger-changelog-0.6.0/lib/changelog/parsers/keep_a_changelog.rb:11:in `parse'
  /Library/Ruby/Gems/2.3.0/gems/danger-changelog-0.6.0/lib/changelog/changelog_file.rb:28:in `parse'
  /Library/Ruby/Gems/2.3.0/gems/danger-changelog-0.6.0/lib/changelog/plugin.rb:76:in `is_changelog_format_correct?'
  /Library/Ruby/Gems/2.3.0/gems/danger-changelog-0.6.0/lib/changelog/plugin.rb:27:in `check!'
  Dangerfile:41:in `eval_file'
  /Library/Ruby/Gems/2.3.0/gems/danger-6.0.9/lib/danger/danger_core/dangerfile.rb:297:in `eval'
  /Library/Ruby/Gems/2.3.0/gems/danger-6.0.9/lib/danger/danger_core/dangerfile.rb:297:in `eval_file'
  /Library/Ruby/Gems/2.3.0/gems/danger-6.0.9/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
  /Library/Ruby/Gems/2.3.0/gems/danger-6.0.9/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
  /Library/Ruby/Gems/2.3.0/gems/danger-6.0.9/lib/danger/danger_core/dangerfile.rb:197:in `parse'
  /Library/Ruby/Gems/2.3.0/gems/danger-6.0.9/lib/danger/danger_core/dangerfile.rb:273:in `run'
  /Library/Ruby/Gems/2.3.0/gems/danger-6.0.9/lib/danger/commands/pr.rb:64:in `block in run'
  /Library/Ruby/Gems/2.3.0/gems/danger-6.0.9/lib/danger/commands/local_helpers/local_setup.rb:43:in `setup'
  /Library/Ruby/Gems/2.3.0/gems/danger-6.0.9/lib/danger/commands/pr.rb:63:in `run'
  /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
  /Library/Ruby/Gems/2.3.0/gems/danger-6.0.9/bin/danger:5:in `<top (required)>'
  /usr/local/bin/danger:22:in `load'
  /usr/local/bin/danger:22:in `<top (required)>'

```

Here is my `CHANGELOG.md`:

```markdown
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

## [0.1.0] - 2019-08-22

### Added

- Initial Project Setup
- ktlint & detekt
- Map Screen
- Danger.systems
- Your change(s) here.


[Unreleased]: https://github.com/Org/Repository/compare/master...HEAD
```

**Comment by dblock** [comment] 2019-08-23 13:18
Strange. I couldn't reproduce. My first guess is that `Regexp#match?` is not defined because some older version of Ruby, but this worked for me at least in specs with 2.3.0. 

Try to add `require 'regexp'` in your Dangerfile to start? If not put up a project with a repro?

**Comment by dblock** [comment] 2019-08-29 12:47
@r0adkll I could reproduce this too. This is because you're using Ruby 2.3.0 which doesn't have `Regexp#match?` which was introduced in Ruby 2.4 (https://blog.cognitohq.com/new-features-in-ruby-2-4/).

Ruby 2.3 was [EOL in march](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/), so I am going to close this as won't fix. 

That said, it's not difficult to fix by using `match` or adding `Regexp#match?`. I would take a PR here that re-adds support for Ruby 2.3.

**Closed by dblock** 2019-08-29 12:47 UTC
Labels: bug?

**Comment by dblock** [comment] 2019-08-29 12:55
Oh and it works in my specs because ActiveSupport defines `Regexp#match?` when it's not available, eg. https://github.com/rails/rails/blob/5d5cbbe0b7ccb35860d8ee097f4213a807f9e92c/activesupport/lib/active_support/core_ext/regexp.rb#L3..L10, but it looks like that's also being removed in newer versions as Ruby 2.3 support is being dropped.

An alternative for you could be to add activesupport to dev dependencies.

**Comment by r0adkll** [comment] 2019-08-29 17:00
Yup! That was my problem, I updated ruby and it went away. Thanks! I'm still pretty new to Ruby.
